### ISSUE TITLE
Diseñar un Mapa de Navegación y un Wireframe

### ISSUE THREAD

**Issue by alhgo** [CIFP-Jose-luis-Garci/kikoru#21]
Dado que el fuerte de este juego son las pantallas y la UI, necesitamos diseñar ya cómo van a ser para empezar a dibujarlas, prestando mucha atención a las zonas interactivas (cuáles son y qué harán: ¿cambiarán de pantallla? ¿Activarán un menú? etc).

Tareas:

- [x] Elaborar un boceto (siempre es mejor comenzar con un dibujo a mano, aunque luego se escenee)
- [x] Pasar ese boceto a un wirframe. 
- [x] Dotar de interactividad al Wireframe para comprobar que funciona a través de un prototipado
- [x] Dotar de capa visual (para ello necesitamos definir paletas de colores, tipografías y, por supuesto, hacer los dibujos

Tanto para hacer el Wirframe como para el prototipado ya os recomendé Figma. Aquí tenéis un tutorial: [Figma desde cero](https://youtu.be/SqO_-olNvnU)

Sería bueno crear una carpeta en el repositorio (fuera del proyecto Unity) para ir subiendo los archivos que vayamos generando

**Comment by alhgo** [comment]
Paso esta tarea a la tarjeta de En Proceso porque quiero pensar que el boceto está hecho (si no, ya estamos tardando, aunque sea a mano en una servilleta)
Cuando esté, @Pablo18-web crea un proyecto en Figma (si no lo tienes ya) y compártelo conmigo con permiso de escritura. Mi usuario es "profesor@laultimapregunta.com", y trabajamos a partir de ahí en el prototipado. Recordad que a medida que vayamos teniendo los diseños definitivos podremos incorporarlos al prototipo y así ver qué tal queda antes de ir a Unity

**Comment by Pablo18-web** [comment]
Buenos dias Álvaro te he enviado la invitación a lo de figma el proyecto lo
hicimos entre marina y yo que somos los resposable del tema interfaz y
interactividad cualquier cosilla dinoslo, lo que te he enviado es un boceto
de la interactividad hemos usado otro nivel al que vamos a utilizar porque
los dibujos estan en proceso y queria visualizar como quedaria esa es
nuestra idea
Un saludo

**Comment by Pablo18-web** [comment]
https://www.figma.com/file/p5cdkxWT57avqYm5edrGr5/wireframe_KIKORU?node-id=20%3A22

**Comment by Marina-santos-jimenez** [comment]
Aquí están los bocetos 
![IMG_20210116_144721](https://user-images.githubusercontent.com/72887273/104813586-5b52c380-580a-11eb-87dc-9783f8bcb632.jpg)
![IMG_20210116_144714](https://user-images.githubusercontent.com/72887273/104813590-63126800-580a-11eb-8196-e463738e40b4.jpg)
![IMG_20210116_144701](https://user-images.githubusercontent.com/72887273/104813592-66a5ef00-580a-11eb-8f1f-da10306c5221.jpg)
![IMG_20210116_144634](https://user-images.githubusercontent.com/72887273/104813599-6c9bd000-580a-11eb-8538-662629d029e4.jpg)

**Comment by alhgo** [comment]
Perfecto. Es lógico que no estén las imágenes finales, porque antes que la capa visual va el diseño de interactividad y los Wireframes. Te comento cosas que veo:

1. El boceto se corresponde con el proyecto de Figma 100%?
2. La primera pantalla solo tiene un botón. Para eso casi mejor una pantalla que se llama "splash", que suele tener un logo animado mientras carga el juego (es para dar emoción) y al pasar un rato ya sale la siguiente pantalla
2. Creo que necesito que me expliquéis mejor cómo funciona el puzzle para entender la mecánica
