### ISSUE TITLE
Animaciones

### ISSUE THREAD

**Issue by alhgo** [CIFP-Jose-luis-Garci/kikoru#22]
Siguiendo el guion que hayamos creado (porque tenemos que tener un guion) deberemos crear escenas animadas para introducir la historia. Las podemos crear haciendo dibujos (aunque sean bocetos) y animarlos mediante la herramienta de animación que hemos "visto" en clase. Mediante programación, vincularemos sonidos a esas animaciones, al añadir "eventos". 

Tareas:

- [x] Definir mediante un guion qué animaciones necesitamos
- [x] Realizar los bocetos
- [x] Importar esas imágenes y animarlas en Unity
- [x] Añadir eventos a las líneas de tiempo de la animación y vincularlos a funciones de código que ejecutarán clips de audio

**Comment by monicavalverdecalvo** [comment]
Bocetos para animación inicial


![2](https://user-images.githubusercontent.com/72887274/104491240-42f86400-55d2-11eb-858f-f269dc186fcd.jpeg)
![1](https://user-images.githubusercontent.com/72887274/104491243-4390fa80-55d2-11eb-87ad-c3655baf7736.jpeg)

**Comment by alhgo** [comment]
Cuando estén definitivos (y con ello me refiero incluso a que estén en un formato que podamos importar a Unity, con el tamaño correcto) subidlos al repositorio para que pueda descargarlos. Y si es posible, acompañadlo de un documento escrito con el guion de las animaciones (para entenderlas mejor) en el que se incluya los sonidos que acompañan, para ir mirándolo. 
Según vayamos teniendo, eso marcad las casillas de completado en la tarea
