### ISSUE TITLE
Elegir tipografía (+guía de color)

### ISSUE THREAD

**Issue by monicavalverdecalvo** [CIFP-Jose-luis-Garci/kikoru#23]
Adjunto un pdf con la guía de color y las diferentes tipografías.

[GUIA DE COLOR Y TIPO KIKORU.pdf](https://github.com/CIFP-Jose-luis-Garci/kikoru/files/5810403/GUIA.DE.COLOR.Y.TIPO.KIKORU.pdf)

- [x] Fuentes Título.
- [x] Fuentes Texto Diálogos.
- [x] Fuentes Diario Kuo.

**Comment by monicavalverdecalvo** [comment]
Fuentes elegidas:

[GUIA DE COLOR Y TIPO KIKORU (1).pdf](https://github.com/CIFP-Jose-luis-Garci/kikoru/files/5810692/GUIA.DE.COLOR.Y.TIPO.KIKORU.1.pdf)

[Inter.zip](https://github.com/CIFP-Jose-luis-Garci/kikoru/files/5810669/Inter.zip)
Licencia libre, personal y comercial.
[adumu.zip](https://github.com/CIFP-Jose-luis-Garci/kikoru/files/5810672/adumu.zip)
Uso educativo, no vender por si sola.
[antio-maisfontes.3af2.zip](https://github.com/CIFP-Jose-luis-Garci/kikoru/files/5810690/antio-maisfontes.3af2.zip)
Gratuito solo de uso personal

Este proyecto es educativo, no se obtendrá beneficio económico de él.

**Comment by alhgo** [comment]
Me parecen perfectas. El pdf con la guía la puedes subir al repositorio, pero las fuentes mejor dejarlas compartidas solo por aquí, para evitar problemas legales. La semana que viene que veremos UI, empezamos a aplicarlas en Unity
