### ISSUE TITLE
Diseño diario

### ISSUE THREAD

**Issue by monicavalverdecalvo** [CIFP-Jose-luis-Garci/kikoru#24]
Crear interface del diario.

Tipo libro.

- [x] Boceto
- [x] Colores.
- [x] Diseño final

**Comment by alhgo** [comment]
Muy importante, y es algo que no lo hemos hablado. Definid el tamaño de la pantalla del juego, por lo menos del tamaño máximo, para que todos los archivos generados tengan ese tamaño.

**Comment by monicavalverdecalvo** [comment]
![BOCETO01](https://user-images.githubusercontent.com/72887274/104820614-4e4bc980-5836-11eb-94cf-eecdcc27ab9c.jpg)

boceto diario.

**Comment by monicavalverdecalvo** [comment]
![BOCETO0101](https://user-images.githubusercontent.com/72887274/104820798-a0d9b580-5837-11eb-8572-298262bcd034.jpg)


boceto diario ajustado a 1920x1080

**Comment by monicavalverdecalvo** [comment]
![BOCETO02](https://user-images.githubusercontent.com/72887274/104849803-01c2c580-58ec-11eb-8d01-09c10ace090e.jpg)

Boceto diario con los colores establecidos

**Comment by monicavalverdecalvo** [comment]
![BOCETO03](https://user-images.githubusercontent.com/72887274/104849830-2cad1980-58ec-11eb-9709-4614fa3530bb.jpg)

Boceto final

**Comment by alhgo** [comment]
Tiene buena pinta. En cuanto el prototipo de Figma esté más definido, podemos incorporarlo para ver qué ta va quedando.
Una cosa importante, que hay que tener en cuenta de cara al UI en Unity, es que hay que tener todo separado por capas: el fondo por un lado y la imagen de los botones por otro (ya que el texto de los botones se pone directamente en Unity)
