### ISSUE TITLE
Creación de escenarios

### ISSUE THREAD

**Issue by monicavalverdecalvo** [CIFP-Jose-luis-Garci/kikoru#27]
Crear los diferentes escenarios:

- [x] Callejón.
- [x] Comisaria.
- [x] Oficina.

Subir bocetos y diseño terminado

**Comment by noelia06** [comment]
![comisaria](https://user-images.githubusercontent.com/72862038/106777333-31403480-6645-11eb-98b5-e28897d7956a.jpg)
Boceto de la comisaria

**Comment by noelia06** [comment]
![callejón](https://user-images.githubusercontent.com/72862038/106777454-4c12a900-6645-11eb-8279-b586ad21b64f.jpg)
Boceto del callejón
