### ISSUE TITLE
Creación de chibis 

### ISSUE THREAD

**Issue by Marina-santos-jimenez** [CIFP-Jose-luis-Garci/kikoru#30]
2 chibis expresiones de ganar y perder puzzle 

- [x] boceto 
- [x] color
- [x] final

**Comment by monicavalverdecalvo** [comment]
Referencia Chibi
![3667e097f7e2a147fd923017aa21398b](https://user-images.githubusercontent.com/72887274/107072641-95e6c500-67e6-11eb-8414-db09026265e6.jpg)

**Comment by monicavalverdecalvo** [comment]
Primer concept de los chibis. 

Pendiente aprobación ;)
