### ISSUE TITLE
concept interfaz

### ISSUE THREAD

**Issue by Marina-santos-jimenez** [CIFP-Jose-luis-Garci/kikoru#31]
creación de concept art de  interfaz y botones 

- [x] boceto
- [x] color
- [x] final

**Comment by Marina-santos-jimenez** [comment]
referencia para interfaz primer cuadro texto todos  puzles   
![image](https://user-images.githubusercontent.com/72887273/106793188-72414480-6657-11eb-9ed9-60d166e3b9c1.png)

referencia cuadro de diálogo 
![image](https://user-images.githubusercontent.com/72887273/106793298-90a74000-6657-11eb-8a57-bd74180a8a5a.png)

**Comment by Marina-santos-jimenez** [comment]
referencia botones inventario 
![image](https://user-images.githubusercontent.com/72887273/106795216-17f5b300-665a-11eb-9d0a-8af770bbb65e.png)
segunda opción
![image](https://user-images.githubusercontent.com/72887273/106795395-4ffcf600-665a-11eb-884f-a7c68355cbfe.png)

referencia interfaz pantalla puzzle  
![image](https://user-images.githubusercontent.com/72887273/106795595-8fc3dd80-665a-11eb-8715-ad79415f76c4.png)

**Comment by noelia06** [comment]
Capeta de Interfaz estaria el cuadro de diálogo final
